[package]
name = "yoku-core"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
chrono = "0.4.42"
diesel = { version = "2.3.3", features = ["postgres", "chrono", "numeric" ] }
diesel-async = { version = "0.7.4", features = ["postgres", "bb8"] }
rust_decimal = { version = "1.39", features = ["diesel"] }
tokio = { version = "1.48.0", features = ["macros", "rt"] }
