[package]
name = "yoku-core"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
diesel = { version = "2.3.3", features = ["postgres", "chrono", "numeric"] }
rust_decimal = { version = "1.39", features = ["diesel"] }
tokio = "1.48.0"
